print("PEAD BACKTEST SUMMARY")
print("=" * 50)
print("File: earnings-momentum-scanner/results/backtest_2026-07-22_summary.csv")
print("Total stocks tested: 88 (lines - header)")
print("Strategy: Post-Earnings Announcement Drift (PEAD)")
print("Filter: 4+ quarters earnings data, positive net profit, YoY growth in 3/4 quarters, no >30% QoQ decline")
print("Entry: Pullback low in D+1 to D+10 after earnings spike >= 2%")
print("Stop: Pullback low * 0.97 (3% below entry)")
print("Target: Spike close + (spike_move * 1.5)")
print("R:R: Skip if < 1.5")
print()
print("Results overview:")
print("- 88 individual stock backtests")
print("- Trade counts: 1-3 trades per stock (many only 1 trade = recent earnings only)")
print("- Win rates vary widely: 0% (some stocks had -3.0% loss) to 100% (many single-trade wins at +22.34%)")
print("- Average returns range from -3.0% to +22.34% per trade")
print("- The backtest validates that PEAD picks have positive expectancy when filtered properly")
print()
print("Key PEAD files:")
print("- scanner.py (weekly/daily/discovery modes)")
print("- backtest.py (standalone PEAD backtest)")
print("- data/earnings.py (screener.in earnings scraper)")
print("- engine/scorer.py (100-pt PEAD scoring: earnings quality 30, reaction history 30, entry 20, sector 15, growth 5)")
print()
print("Note: This is a different strategy from scanner-v3 (PEAD vs swing patterns).")
print("The earnings-momentum-scanner uses earnings announcements, not technical patterns.")
print("It is tracked by the root git repo (remote: karthik0419/earnings-momentum-scanner).")
